import mongoose from 'mongoose';
const Schema = mongoose.Schema;

const DataSchema = new Schema({
    'epoch_time' : { type: 'String', required: true },
    'SYS_0_HEADER' : { type: 'String', required: true },
    'SYS_0_EPOCH' :  { type: 'String', required: true },
    'SYS_0_TIME' :  { type: 'String', required: true },
    'THM_0_CDH' :  { type: 'String', required: true },
    'THM_1_BATT' :  { type: 'String', required: true },
    'THM_2_UHF_PA' :  { type: 'String', required: true },
    'THM_2_FPGA' :  { type: 'String', required: true },
    'THM_3_ADCS' :  { type: 'String', required: true },
    'THM_3_X_MOTOR' :  { type: 'String', required: true },
    'THM_3_Y_MOTOR' :  { type: 'String', required: true },
    'THM_3_Z_MOTOR' :  { type: 'String', required: true },
    'THM_4_MOTOR' :  { type: 'String', required: true },
    'THM_4_PIN_SWITCH_DIODE' :  { type: 'String', required: true },
    'EPS_0_12V' :  { type: 'String', required: true },
    'EPS_1_12V' :  { type: 'String', required: true },
    'EPS_2_BATT' :  { type: 'String', required: true },
    'EPS_3_BATT' :  { type: 'String', required: true },
    'EPS_4_SOC' :  { type: 'String', required: true },
    'ADCS_0_MRP_1' :  { type: 'String', required: true },
    'ADCS_0_MRP_2' :  { type: 'String', required: true },
    'ADCS_0_MRP_3' :  { type: 'String', required: true },
    'ADCS_3_X_WHEEL' :  { type: 'String', required: true },
    'ADCS_3_Y_WHEEL' :  { type: 'String', required: true },
    'ADCS_3_Z_WHEEL' :  { type: 'String', required: true },
    'ADCS_1_RATE_X' :  { type: 'String', required: true },
    'ADCS_1_RATE_Y' :  { type: 'String', required: true },
    'ADCS_1_RATE_Z' :  { type: 'String', required: true },
    'ADCS_1_MAG_FIELD_X' :  { type: 'String', required: true },
    'ADCS_1_MAG_FIELD_Y' :  { type: 'String', required: true },
    'ADCS_1_MAG_FIELD_Z' :  { type: 'String', required: true },
    'ADCS_5_TSLL' :  { type: 'String', required: true },
    'GPS_0_TOW' :  { type: 'String', required: true },
    'GPS_0_WEEK' :  { type: 'String', required: true },
    'GPS_1_X' : { type: 'String', required: true },
    'GPS_1_Y' : { type: 'String', required: true },
    'GPS_1_Z' : { type: 'String', required: true },
    'GPS_2_X' : { type: 'String', required: true },
    'GPS_2_Y' : { type: 'String', required: true },
    'GPS_2_Z' : { type: 'String', required: true },
    'SYS_0_FOOTER' : { type: 'String', required: true },
});

export default mongoose.model('Data', DataSchema, 'beacons');
